### ISSUE TITLE
Need more whitespace around the text content in the side bar

### ISSUE THREAD

**Issue by rgdonohue** [josh-wadlington/offshore-wind#3]
Try more padding on the container element, and if that doesn't work, padding on the individual elements themselves.

Love the turbine graphic!

![image](https://user-images.githubusercontent.com/1952205/33839832-7e533d7e-de50-11e7-8573-a6282c1f9c56.png)

**Comment by josh-wadlington** [comment]
Added padding to all sides of the container element. 

Thanks for the kudos on the graphic, it was a good learning experience figuring out how to make that work.
