### ISSUE TITLE
User needs an indication what the lessee areas are?

### ISSUE THREAD

**Issue by rgdonohue** [josh-wadlington/offshore-wind#6]
Indicate what these are with a graphic, either in the side panel or on the legend?

Also, you spell it "lease" in the sidebar and lessee in the hover.

![image](https://user-images.githubusercontent.com/1952205/33840234-9555b8a2-de51-11e7-8f9e-d321ac22bef3.png)

**Comment by rgdonohue** [comment]
Lease and lessee are different things?

**Comment by josh-wadlington** [comment]
Revised the side panel with additional language to clarify what the areas represent and to differentiate between lease and lessee. 

In this case the Lease is the geographic area and terms and conditions placed upon it  - the Lessee is the leaseholder or company that holds the lease. The lessee holds the exclusive rights to develop the area. 

Whew, that is about the extent of my ability to explain the legalese of contract law.
